services:
  redis:
    image: redis:7.2.4-alpine3.19
    environment: 
      - TZ=America/New_York
    hostname: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      # Change the host port if there is a conflict
      - 6379:6379/tcp
    volumes:
      - "./redis-data:/data"
      - "./redis-conf:/usr/local/etc/redis:ro"
    restart: always
    volumes_from:
    - tmp
    depends_on:
      - tmp
  unbound:
    image: crazymax/unbound:1.19.3
    hostname: unbound
    environment: 
      - TZ=America/New_York
    depends_on:
      - redis
      - tmp
    volumes:
      - "./unbound-config:/config:ro"
      - "./unbound-keys:/etc/unbound/keys"
    restart: always
    expose:
      - "5053"
    volumes_from:
      - tmp
  tmp:
      image: busybox:1.36.1
      command: chmod -R 777 /tmp/docker
      volumes:
          - /tmp/docker        
  pihole:
      image: pihole/pihole:development-v6
      hostname: ${PIHOLE_HOSTNAME:-pihole}
      dns:
        - 127.0.0.1
        - 8.8.8.8
      ports:
        - "53:53/tcp"
        - "53:53/udp"
         # Change the host port if there is a conflict
        - "80:80/tcp"
        - "443:443/tcp"
      environment:
        TZ: 'America/New_York'
        FTLCONF_dns_upstreams: 'unbound#5053' 
        FTLCONF_dns_listeningMode : 'all' # needed when docker in bridge network mode
        FTLCONF_dns_cache_optimizer: -1 # disable serve expired at the pihole layer (unbound will do this)
        FTLCONF_dns_rateLimit_count: 0
        FTLCONF_dns_rateLimit_interval: 0
        FTLCONF_webserver_session_timeout: ${PIHOLE_SESSION_TIMEOUT:-2592000}
        FTLCONF_database_maxDBdays: 8 # reduced from 91
        # Volumes store your data between container upgrades
      volumes:
        - './etc-pihole:/etc/pihole'
        - './etc-dnsmasq.d:/etc/dnsmasq.d'
      #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      depends_on:
        - unbound
      restart: unless-stopped